categories: 
  - "CompBio Galaxy Wrappers"
homepage_url: http://califano.c2b2.columbia.edu/viper
owner: creason
remote_repository_url: https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/viper
repositories:
  run_viper:
    description: "Virtual Inference of Protein-activity by Enriched Regulon analysis."
    include:
      - run_viper.xml
      - macros.xml
  viper_report:
    description: "Generate Viper Report for a gene of interest."
    include:
      - viper_report.xml
      - macros.xml
  run_aracne2regulons:
    description: "Builds regulons from an aracne network."
    include:
      - run_aracne2regulons.xml
      - macros.xml
