owner: "patterja"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/drug_prediction_report"
categories:
  - "CompBio Galaxy Wrappers"
description: "Drug Prediction Report"
repositories:
  ruvseq:
    include: 
      - drugprediction_report.xml
