owner: "campbena"
remote_repository_url: "https://github.com/broadinstitute/gatk/tree/4.0.5.1"
homepage_url: "https://gatk.broadinstitute.org/hc/en-us/sections/360007381571-4-0-5-1"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  gatk4_variantrecalibrator:
    description: "Build a recalibration model to score variant quality for filtering purposes."
    include:
      - macros.xml
      - gatk4_variantrecalibrator.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_applyvqsr:
    description: "Apply a score cutoff to filter variants based on a recalibration table"
    include:
      - macros.xml
      - gatk4_applyvqsr.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
