name: "rgrnastar"
owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/rgrnastar"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  rgrnastar:
    description: "Gapped-read mapper for RNA-seq data"
    include:
      - rg_rnaStar.xml
      - macros.xml
      - tool_data_table_conf.xml.sample
      - test-data/*
      - tool-data/*
