owner: "creason"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/picard2"
homepage_url: "https://broadinstitute.github.io/picard/"
categories:
  - "KDL Tools"
suite:
  name: "picard2"
  description: "Picard suite of tools for manipulating high-throughput sequencing (HTS) data"
  include_repositories:
  - name: "picard_AddCommentsToBam"
    owner: creason
  - name: "picard_AddOrReplaceReadGroups"
    owner: creason
  - name: "picard_BedToIntervalList"
    owner: creason
  - name: "picard_CleanSam"
    owner: creason
  - name: "picard_CASM"
    owner: creason
  - name: "picard_CollectBaseDistributionByCycle"
    owner: creason
  - name: "picard_CollectGcBiasMetrics"
    owner: creason
  - name: "picard_CollectInsertSizeMetrics"
    owner: creason
  - name: "picard_CollectRnaSeqMetrics"
    owner: creason
  - name: "picard_CollectWgsMetrics"
    owner: creason
  - name: "picard_DownsampleSam"
    owner: creason
  - name: "picard_EstimateLibraryComplexity"
    owner: creason
  - name: "picard_FastqToSam"
    owner: creason
  - name: "picard_FilterSamReads"
    owner: creason
  - name: "picard_MarkDuplicates"
    owner: creason
  - name: "picard_MarkDuplicatesWithMateCigar"
    owner: creason
  - name: "picard_MeanQualityByCycle"
    owner: creason
  - name: "picard_MergeBamAlignment"
    owner: creason
  - name: "picard_MergeSamFiles"
    owner: creason
  - name: "picard_NormalizeFasta"
    owner: creason
  - name: "picard_QualityScoreDistribution"
    owner: creason
  - name: "picard_ReorderSam"
    owner: creason
  - name: "picard_ReplaceSamHeader"
    owner: creason
  - name: "picard_RevertOriginalBaseQualitiesAndAddMateCigar"
    owner: creason
  - name: "picard_RevertSam"
    owner: creason
  - name: "picard_SamToFastq"
    owner: creason
  - name: "picard_SortSam"
    owner: creason
  - name: "picard_ValidateSamFile"

