owner: "patterja"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/ruvseq"
categories:
  - "CompBio Galaxy Wrappers"
description: "Removal of Unwanted Variation on RNASeq Data"
repositories:
  ruvseq:
    include: 
      - RUVs.xml
      - RUVs.R
      
