owner: "creason"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cnvkit"
homepage_url: "https://cnvkit.readthedocs.io/en/stable/pipeline.html"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  cnvkit:
    description: "Command line toolkit for copy number analysis"
    include:
        - cnvkit_batch.xml
        - cnvkit_call.xml
        - cnvkit_heatmap.xml
        - macros.xml
        - tool_data_table_conf.xml.sample
        - tool-data/*
