owner: "campbena"
remote_repository_url: "https://github.com/NEleanor/compbio-galaxy-wrappers/tree/master/gatk_germline_cnv"
homepage_url: "https://github.com/NEleanor/compbio-galaxy-wrappers/tree/master/gatk_germline_cnv"
categories:
  - "KDL Tools"
repositories:
  moon_gatk_cnv_formatter:
    description: "formats the segments file from PostProcessGermlineCNVs to be compatible with Moon."
    include:
      - moon_gatk_cnv_formater.py
      - moon_cnv_formater.xml
