package:
    name: gatk4-python
    version: 4.1.4.1
source:
    sha256: 21ae694cfc8b7447381ad5ce62ed4af22e53a228b12495bdcca7df0c73b09cea
    url: https://github.com/broadinstitute/gatk/releases/download/4.1.4.1/gatk-4.1.4.1.zip
build:
    noarch: generic
    number: '0'
    string: '0'
    
requirements:
    build:
        - pip=9.0.1=py36_1
    run:
        - python
        - pip
        - certifi=2016.2.28=py36_0
        - intel-openmp=2018.0.0
        - mkl=2018.0.1
        - mkl-service=1.1.2
        - defaults::numpy==1.13.3
        - openssl=1.0.2l=0
        - pip=9.0.1=py36_1
        - python=3.6.2=0
        - readline=6.2=2
        - setuptools=36.4.0=py36_1
        - sqlite=3.13.0=0
        - anaconda::tensorflow=1.12.0
        - tk=8.5.18=0
        - wheel=0.29.0=py36_0
        - xz=5.2.3=0
        - zlib=1.2.11=0
test:
    commands:
about:
    dev_url: https://github.com/broadinstitute/gatk
    home: https://www.broadinstitute.org/gatk/
    license: BSD-3-Clause
    license_family: BSD
    summary: Genome Analysis Toolkit (GATK4)
extra:
    copy_test_source_files: true
    final: true
        