owner: "campbena"
remote_repository_url: "https://github.com/broadinstitute/gatk/tree/4.0.5.1"
homepage_url: "https://gatk.broadinstitute.org/hc/en-us/sections/360007381571-4-0-5-1"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  gatk4_combinegvcfs:
    description: "Merges one or more HaplotypeCaller GVCF files into a single GVCF with appropriate annotations"
    include:
      - macros.xml
      - gatk4_combinegvcfs.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_genotypegvcfs:
    description: "Perform joint genotyping on one or more samples pre-called with HaplotypeCaller"
    include:
      - macros.xml
      - gatk4_genotypegvcfs.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_collectreadcounts_qiaseq:
    description: "Collects read counts at specified intervals"
    include:
      - macros.xml
      - gatk4_collectreadcounts.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_selectvariants:
    description: "Select a subset of variants from a VCF file"
    include:
      - macros.xml
      - gatk4_selectvariants.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_denoisereadcounts:
    description: "Denoises read counts to produce denoised copy ratios"
    include:
      - macros.xml
      - gatk4_denoisereadcounts.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_modelsegments:
    description: "Models segmented copy ratios from denoised read counts and segmented minor-allele fractions from allelic counts"
    include:
      - macros.xml
      - gatk4_modelsegments.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_callcopyratiosegments:
    description: "Calls copy-ratio segments as amplified, deleted, or copy-number neutral"
    include:
      - macros.xml
      - gatk4_callcopyratiosegments.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_plotmodeledsegments:
    description: "Creates plots of denoised and segmented copy-ratio and minor-allele-fraction estimates"
    include:
      - macros.xml
      - gatk4_plotmodeledsegments.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
